# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ganidhu/Desktop/engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ganidhu/Desktop/engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ganidhu/Desktop/engine/CMakeFiles /home/ganidhu/Desktop/engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ganidhu/Desktop/engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cmake-good

# Build rule for target.
cmake-good: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cmake-good
.PHONY : cmake-good

# fast build rule for target.
cmake-good/fast:
	$(MAKE) -f CMakeFiles/cmake-good.dir/build.make CMakeFiles/cmake-good.dir/build
.PHONY : cmake-good/fast

#=============================================================================
# Target rules for targets named engine_draw

# Build rule for target.
engine_draw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine_draw
.PHONY : engine_draw

# fast build rule for target.
engine_draw/fast:
	$(MAKE) -f CMakeFiles/engine_draw.dir/build.make CMakeFiles/engine_draw.dir/build
.PHONY : engine_draw/fast

#=============================================================================
# Target rules for targets named swapchain_support

# Build rule for target.
swapchain_support: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 swapchain_support
.PHONY : swapchain_support

# fast build rule for target.
swapchain_support/fast:
	$(MAKE) -f CMakeFiles/swapchain_support.dir/build.make CMakeFiles/swapchain_support.dir/build
.PHONY : swapchain_support/fast

#=============================================================================
# Target rules for targets named error_setup

# Build rule for target.
error_setup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 error_setup
.PHONY : error_setup

# fast build rule for target.
error_setup/fast:
	$(MAKE) -f CMakeFiles/error_setup.dir/build.make CMakeFiles/error_setup.dir/build
.PHONY : error_setup/fast

#=============================================================================
# Target rules for targets named engine_graphics

# Build rule for target.
engine_graphics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine_graphics
.PHONY : engine_graphics

# fast build rule for target.
engine_graphics/fast:
	$(MAKE) -f CMakeFiles/engine_graphics.dir/build.make CMakeFiles/engine_graphics.dir/build
.PHONY : engine_graphics/fast

#=============================================================================
# Target rules for targets named engine_init

# Build rule for target.
engine_init: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine_init
.PHONY : engine_init

# fast build rule for target.
engine_init/fast:
	$(MAKE) -f CMakeFiles/engine_init.dir/build.make CMakeFiles/engine_init.dir/build
.PHONY : engine_init/fast

#=============================================================================
# Target rules for targets named queue_data

# Build rule for target.
queue_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 queue_data
.PHONY : queue_data

# fast build rule for target.
queue_data/fast:
	$(MAKE) -f CMakeFiles/queue_data.dir/build.make CMakeFiles/queue_data.dir/build
.PHONY : queue_data/fast

#=============================================================================
# Target rules for targets named engine_window

# Build rule for target.
engine_window: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine_window
.PHONY : engine_window

# fast build rule for target.
engine_window/fast:
	$(MAKE) -f CMakeFiles/engine_window.dir/build.make CMakeFiles/engine_window.dir/build
.PHONY : engine_window/fast

#=============================================================================
# Target rules for targets named engine_main

# Build rule for target.
engine_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine_main
.PHONY : engine_main

# fast build rule for target.
engine_main/fast:
	$(MAKE) -f CMakeFiles/engine_main.dir/build.make CMakeFiles/engine_main.dir/build
.PHONY : engine_main/fast

lib/eng_window.o: lib/eng_window.cpp.o

.PHONY : lib/eng_window.o

# target to build an object file
lib/eng_window.cpp.o:
	$(MAKE) -f CMakeFiles/engine_window.dir/build.make CMakeFiles/engine_window.dir/lib/eng_window.cpp.o
.PHONY : lib/eng_window.cpp.o

lib/eng_window.i: lib/eng_window.cpp.i

.PHONY : lib/eng_window.i

# target to preprocess a source file
lib/eng_window.cpp.i:
	$(MAKE) -f CMakeFiles/engine_window.dir/build.make CMakeFiles/engine_window.dir/lib/eng_window.cpp.i
.PHONY : lib/eng_window.cpp.i

lib/eng_window.s: lib/eng_window.cpp.s

.PHONY : lib/eng_window.s

# target to generate assembly for a file
lib/eng_window.cpp.s:
	$(MAKE) -f CMakeFiles/engine_window.dir/build.make CMakeFiles/engine_window.dir/lib/eng_window.cpp.s
.PHONY : lib/eng_window.cpp.s

lib/engine.o: lib/engine.cpp.o

.PHONY : lib/engine.o

# target to build an object file
lib/engine.cpp.o:
	$(MAKE) -f CMakeFiles/engine_main.dir/build.make CMakeFiles/engine_main.dir/lib/engine.cpp.o
.PHONY : lib/engine.cpp.o

lib/engine.i: lib/engine.cpp.i

.PHONY : lib/engine.i

# target to preprocess a source file
lib/engine.cpp.i:
	$(MAKE) -f CMakeFiles/engine_main.dir/build.make CMakeFiles/engine_main.dir/lib/engine.cpp.i
.PHONY : lib/engine.cpp.i

lib/engine.s: lib/engine.cpp.s

.PHONY : lib/engine.s

# target to generate assembly for a file
lib/engine.cpp.s:
	$(MAKE) -f CMakeFiles/engine_main.dir/build.make CMakeFiles/engine_main.dir/lib/engine.cpp.s
.PHONY : lib/engine.cpp.s

lib/engine_draw.o: lib/engine_draw.cpp.o

.PHONY : lib/engine_draw.o

# target to build an object file
lib/engine_draw.cpp.o:
	$(MAKE) -f CMakeFiles/engine_draw.dir/build.make CMakeFiles/engine_draw.dir/lib/engine_draw.cpp.o
.PHONY : lib/engine_draw.cpp.o

lib/engine_draw.i: lib/engine_draw.cpp.i

.PHONY : lib/engine_draw.i

# target to preprocess a source file
lib/engine_draw.cpp.i:
	$(MAKE) -f CMakeFiles/engine_draw.dir/build.make CMakeFiles/engine_draw.dir/lib/engine_draw.cpp.i
.PHONY : lib/engine_draw.cpp.i

lib/engine_draw.s: lib/engine_draw.cpp.s

.PHONY : lib/engine_draw.s

# target to generate assembly for a file
lib/engine_draw.cpp.s:
	$(MAKE) -f CMakeFiles/engine_draw.dir/build.make CMakeFiles/engine_draw.dir/lib/engine_draw.cpp.s
.PHONY : lib/engine_draw.cpp.s

lib/engine_graphics.o: lib/engine_graphics.cpp.o

.PHONY : lib/engine_graphics.o

# target to build an object file
lib/engine_graphics.cpp.o:
	$(MAKE) -f CMakeFiles/engine_graphics.dir/build.make CMakeFiles/engine_graphics.dir/lib/engine_graphics.cpp.o
.PHONY : lib/engine_graphics.cpp.o

lib/engine_graphics.i: lib/engine_graphics.cpp.i

.PHONY : lib/engine_graphics.i

# target to preprocess a source file
lib/engine_graphics.cpp.i:
	$(MAKE) -f CMakeFiles/engine_graphics.dir/build.make CMakeFiles/engine_graphics.dir/lib/engine_graphics.cpp.i
.PHONY : lib/engine_graphics.cpp.i

lib/engine_graphics.s: lib/engine_graphics.cpp.s

.PHONY : lib/engine_graphics.s

# target to generate assembly for a file
lib/engine_graphics.cpp.s:
	$(MAKE) -f CMakeFiles/engine_graphics.dir/build.make CMakeFiles/engine_graphics.dir/lib/engine_graphics.cpp.s
.PHONY : lib/engine_graphics.cpp.s

lib/engine_init.o: lib/engine_init.cpp.o

.PHONY : lib/engine_init.o

# target to build an object file
lib/engine_init.cpp.o:
	$(MAKE) -f CMakeFiles/engine_init.dir/build.make CMakeFiles/engine_init.dir/lib/engine_init.cpp.o
.PHONY : lib/engine_init.cpp.o

lib/engine_init.i: lib/engine_init.cpp.i

.PHONY : lib/engine_init.i

# target to preprocess a source file
lib/engine_init.cpp.i:
	$(MAKE) -f CMakeFiles/engine_init.dir/build.make CMakeFiles/engine_init.dir/lib/engine_init.cpp.i
.PHONY : lib/engine_init.cpp.i

lib/engine_init.s: lib/engine_init.cpp.s

.PHONY : lib/engine_init.s

# target to generate assembly for a file
lib/engine_init.cpp.s:
	$(MAKE) -f CMakeFiles/engine_init.dir/build.make CMakeFiles/engine_init.dir/lib/engine_init.cpp.s
.PHONY : lib/engine_init.cpp.s

lib/error_setup.o: lib/error_setup.cpp.o

.PHONY : lib/error_setup.o

# target to build an object file
lib/error_setup.cpp.o:
	$(MAKE) -f CMakeFiles/error_setup.dir/build.make CMakeFiles/error_setup.dir/lib/error_setup.cpp.o
.PHONY : lib/error_setup.cpp.o

lib/error_setup.i: lib/error_setup.cpp.i

.PHONY : lib/error_setup.i

# target to preprocess a source file
lib/error_setup.cpp.i:
	$(MAKE) -f CMakeFiles/error_setup.dir/build.make CMakeFiles/error_setup.dir/lib/error_setup.cpp.i
.PHONY : lib/error_setup.cpp.i

lib/error_setup.s: lib/error_setup.cpp.s

.PHONY : lib/error_setup.s

# target to generate assembly for a file
lib/error_setup.cpp.s:
	$(MAKE) -f CMakeFiles/error_setup.dir/build.make CMakeFiles/error_setup.dir/lib/error_setup.cpp.s
.PHONY : lib/error_setup.cpp.s

lib/queue.o: lib/queue.cpp.o

.PHONY : lib/queue.o

# target to build an object file
lib/queue.cpp.o:
	$(MAKE) -f CMakeFiles/queue_data.dir/build.make CMakeFiles/queue_data.dir/lib/queue.cpp.o
.PHONY : lib/queue.cpp.o

lib/queue.i: lib/queue.cpp.i

.PHONY : lib/queue.i

# target to preprocess a source file
lib/queue.cpp.i:
	$(MAKE) -f CMakeFiles/queue_data.dir/build.make CMakeFiles/queue_data.dir/lib/queue.cpp.i
.PHONY : lib/queue.cpp.i

lib/queue.s: lib/queue.cpp.s

.PHONY : lib/queue.s

# target to generate assembly for a file
lib/queue.cpp.s:
	$(MAKE) -f CMakeFiles/queue_data.dir/build.make CMakeFiles/queue_data.dir/lib/queue.cpp.s
.PHONY : lib/queue.cpp.s

lib/swapchain_support.o: lib/swapchain_support.cpp.o

.PHONY : lib/swapchain_support.o

# target to build an object file
lib/swapchain_support.cpp.o:
	$(MAKE) -f CMakeFiles/swapchain_support.dir/build.make CMakeFiles/swapchain_support.dir/lib/swapchain_support.cpp.o
.PHONY : lib/swapchain_support.cpp.o

lib/swapchain_support.i: lib/swapchain_support.cpp.i

.PHONY : lib/swapchain_support.i

# target to preprocess a source file
lib/swapchain_support.cpp.i:
	$(MAKE) -f CMakeFiles/swapchain_support.dir/build.make CMakeFiles/swapchain_support.dir/lib/swapchain_support.cpp.i
.PHONY : lib/swapchain_support.cpp.i

lib/swapchain_support.s: lib/swapchain_support.cpp.s

.PHONY : lib/swapchain_support.s

# target to generate assembly for a file
lib/swapchain_support.cpp.s:
	$(MAKE) -f CMakeFiles/swapchain_support.dir/build.make CMakeFiles/swapchain_support.dir/lib/swapchain_support.cpp.s
.PHONY : lib/swapchain_support.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/cmake-good.dir/build.make CMakeFiles/cmake-good.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/cmake-good.dir/build.make CMakeFiles/cmake-good.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/cmake-good.dir/build.make CMakeFiles/cmake-good.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... cmake-good"
	@echo "... engine_draw"
	@echo "... swapchain_support"
	@echo "... error_setup"
	@echo "... engine_graphics"
	@echo "... engine_init"
	@echo "... queue_data"
	@echo "... engine_window"
	@echo "... rebuild_cache"
	@echo "... engine_main"
	@echo "... lib/eng_window.o"
	@echo "... lib/eng_window.i"
	@echo "... lib/eng_window.s"
	@echo "... lib/engine.o"
	@echo "... lib/engine.i"
	@echo "... lib/engine.s"
	@echo "... lib/engine_draw.o"
	@echo "... lib/engine_draw.i"
	@echo "... lib/engine_draw.s"
	@echo "... lib/engine_graphics.o"
	@echo "... lib/engine_graphics.i"
	@echo "... lib/engine_graphics.s"
	@echo "... lib/engine_init.o"
	@echo "... lib/engine_init.i"
	@echo "... lib/engine_init.s"
	@echo "... lib/error_setup.o"
	@echo "... lib/error_setup.i"
	@echo "... lib/error_setup.s"
	@echo "... lib/queue.o"
	@echo "... lib/queue.i"
	@echo "... lib/queue.s"
	@echo "... lib/swapchain_support.o"
	@echo "... lib/swapchain_support.i"
	@echo "... lib/swapchain_support.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

